# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

# pipelines - stages - jobs - tasks(steps)

jobs:
  - job: Job_1
    steps:
    - script: echo == JOB -1- Hello, world AGAIN!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo ======== more info
      displayName: 'Run a multi-line script'
  - job: Job_2
    steps:
      - script: echo == JOB -2-!