trigger:
  - main

#strategy:
#  matrix:
#    linux: 
#      operatingSystem: 'ubuntu-latest'
#    mac:
#      operatingSystem: 'macos-latest'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build_st
    jobs:
      - job: Build_Job
        steps: 
          - bash: echo "Do the build"
  - stage: dev_Deploy_st
    jobs:
      - deployment: dev_Deploy_deployment
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo deploy to DEV deployment-job
  - stage: qa_Deploy_st
    jobs:
      - deployment: qa_Deploy_deployment
        environment: qa
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo deploy to QA deployment-job