trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publick_key
  inputs:
    secureFile: 'azure_rsa.pub'
    retryCount: '5'
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publick_key.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'itkon_be_storage'
    backendAzureRmContainerName: 'storage_account_itkon_container'
    backendAzureRmKey: 'kuber-dev.tfstate'
    allowTelemetryCollection: true
- task: TerraformCLI@2
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/azure/kubernetes'
    environmentServiceName: 'azure-resource-manager'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publick_key.secureFilePath)'
